name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install tools (battlesnake cli)
      run: go install github.com/BattlesnakeOfficial/rules/cli/battlesnake

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
